### create auction

POST http://localhost:8080/auction HTTP/1.1
content-type: application/json

{
    "product_name": "Calhambeque",
    "category": "Carros",
    "description": "esta é uma descrição completa",
    "condition": 1
}

### create bid
POST http://localhost:8080/bid HTTP/1.1
content-type: application/json

{
    "user_id": "00000000-0000-0000-0000-000000000001",
    "auction_id": "0f508ee5-4b8f-492e-974a-7dfed88aaa64",
    "amount": 10
}

### get auction
GET http://localhost:8080/auction/0f508ee5-4b8f-492e-974a-7dfed88aaa64 HTTP/1.1
